#pragma once

#include <cstdint>
#include "nn_defs10.h"

// USE_INT16 is provided by:
//   - aieml build: config_gen.h (generated by aieml/Makefile from PRECISION)
//   - host build : -DUSE_INT16 passed on the compiler command line
// __has_include lets aieml pull in its generated header without breaking host.
#if __has_include("config_gen.h")
  #include "config_gen.h"
#endif

#ifdef USE_INT16
using DATA_TYPE = std::int16_t;
#else
using DATA_TYPE = float;
#endif

// AIE vector width is 256 bits. The first dense layer's column count must be a
// multiple of the native vector element count for DATA_TYPE, so INPUT_SIZE is
// rounded up to GRAPH_INPUT_SIZE. Shared between graph (aieml/graph.h) and
// host (host/host.cpp) so weight/GMIO sizing stays in lock-step.
constexpr unsigned VECTOR_BITS        = 256;
constexpr unsigned ALIGNMENT_ELEMENTS = VECTOR_BITS / (sizeof(DATA_TYPE) * 8);
constexpr unsigned GRAPH_INPUT_SIZE =
    (INPUT_SIZE + ALIGNMENT_ELEMENTS - 1) / ALIGNMENT_ELEMENTS * ALIGNMENT_ELEMENTS;
