// ===========================================================================
//  C simulation testbench.
//
//  WHAT IT CHECKS, and why that changed
//  It used to compare against punit/outputs/hls_27dim.txt, which was itself an
//  ap_fixed<16,6> / alpha=0.125 csim dump. That made the test tautological:
//  it could only ever confirm that the design still had the old format's
//  error, and it passed while the design was 50% off the real network.
//
//  Now it compares against the NATIVE model (pl_fixed/native/run_model.cpp),
//  which compiles these exact kernel sources with g++. Same arithmetic, a
//  different compiler and no HLS front end, so agreement should be to float
//  round-off -- and a disagreement means the HLS toolchain changed the
//  semantics of the C++, which is precisely what csim exists to catch.
//
//  The reference is regenerated by `make csim`, so it can never go stale
//  against a format change.
// ===========================================================================
#include <cmath>
#include <cstdio>
#include <cstdlib>
#include <fstream>
#include <iostream>
#include <map>
#include <string>
#include <vector>

#include "rtda_split_top.h"

// Required by nnet_helpers.h
namespace nnet {
bool trace_enabled = false;
std::map<std::string, void*>* trace_outputs = nullptr;
size_t trace_type_size = sizeof(double);
}

// Settings come from the environment, not -D. A string -D loses its quotes
// somewhere between Tcl and the csim makefile Vitis generates; see the same
// note in rtda_fixed.h. The Makefile exports these.
#define STRIDE 8

static const char* env_or(const char* k, const char* dflt) {
    const char* v = std::getenv(k);
    return (v && *v) ? v : dflt;
}

int main() {
    const std::string stim = env_or("RTDA_STIMULUS", "embed_input.txt");
    const std::string refp = env_or("RTDA_TB_REFERENCE", "tb_means.txt");
    const int n_events = std::atoi(env_or("RTDA_EVENTS", "2"));
    const int warmup = std::atoi(env_or("RTDA_WARMUP", "3"));

    std::vector<float> raw;
    {
        std::ifstream f(stim);
        if (!f) { std::cerr << "ERROR: cannot open " << stim << "\n"; return 1; }
        float v;
        while (f >> v && (int)raw.size() < n_events * MAX_TRACKS * STRIDE)
            raw.push_back(v);
    }
    if ((int)raw.size() < n_events * MAX_TRACKS * STRIDE) {
        std::cerr << "ERROR: " << stim << " has only " << raw.size()
                  << " values, need " << n_events * MAX_TRACKS * STRIDE << "\n";
        return 1;
    }

    // Reference: "<n_events> 128" header then one row per event.
    int ref_ev = 0, ref_cols = 0;
    std::vector<float> ref;
    {
        std::ifstream f(refp);
        if (!f) {
            std::cerr << "ERROR: cannot open " << refp
                      << " -- `make csim` regenerates it\n";
            return 1;
        }
        f >> ref_ev >> ref_cols;
        ref.resize((size_t)ref_ev * ref_cols);
        for (size_t i = 0; i < ref.size(); i++) f >> ref[i];
        if (ref_cols != HIDDEN) {
            std::cerr << "ERROR: reference has " << ref_cols
                      << " columns, expected " << HIDDEN << "\n";
            return 1;
        }
    }
    const int n_cmp = (n_events < ref_ev) ? n_events : ref_ev;

    std::printf("\ncsim: %d event(s), warmup=%d, ap_fixed<%d,%d> alpha=%g\n",
                n_events, warmup, RTDA_W, RTDA_I, (double)RTDA_ALPHA_VALUE);
    std::printf("reference: %s (native model, %d events)\n\n", refp.c_str(), ref_ev);

    // Stage every event, then ONE call -- the kernel loops over events itself.
    // Exercising the multi-event path is the point: a testbench that still
    // called it once per event would pass without ever running the event loop
    // this design now depends on.
    std::vector<float> track((size_t)n_cmp * MAX_TRACKS * INPUT_SIZE);
    std::vector<float> mean((size_t)n_cmp * HIDDEN);
    std::vector<float> out27((size_t)n_cmp * OUT_DIM);

    for (int ev = 0; ev < n_cmp; ev++) {
        const float* base = raw.data() + (size_t)ev * MAX_TRACKS * STRIDE;
        float* dst = track.data() + (size_t)ev * MAX_TRACKS * INPUT_SIZE;
        for (int j = 0; j < MAX_TRACKS; j++)
            for (int i = 0; i < INPUT_SIZE; i++)
                dst[j * INPUT_SIZE + i] = base[j * STRIDE + i];
    }

    rtda_split_top(track.data(), mean.data(), out27.data(),
                   n_cmp, MAX_TRACKS, warmup, true);

    float worst = 0.0f;
    int worst_ev = 0;
    for (int ev = 0; ev < n_cmp; ev++) {
        float d = 0.0f;
        for (int k = 0; k < HIDDEN; k++)
            d = std::max(d, std::fabs(mean[(size_t)ev * HIDDEN + k]
                                      - ref[(size_t)ev * HIDDEN + k]));
        std::printf("  event %3d   max|diff| vs native = %.3e\n", ev, d);
        if (d > worst) { worst = d; worst_ev = ev; }
    }

    // Both sides run the same source. Anything above float round-off means the
    // HLS front end and g++ disagree about what this C++ computes.
    const float TOL = 1e-5f;
    std::printf("\nworst: %.3e (event %d)   tolerance %.1e\n", worst, worst_ev, TOL);
    if (worst < TOL) { std::printf("PASS\n"); return 0; }
    std::printf("FAIL -- HLS csim does not match the native model\n");
    return 1;
}
