#!/usr/bin/env bash
# ****************************************************************************
# Vivado (TM) v2024.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : AMD Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Mon Aug 04 21:45:04 EDT 2025
# SW Build 5239630 on Fri Nov 08 22:34:34 MST 2024
#
# Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
# Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
[ -z "$LIBRARY_PATH" ] && export LIBRARY_PATH=/usr/lib/x86_64-linux-gnu || export LIBRARY_PATH=/usr/lib/x86_64-linux-gnu:$LIBRARY_PATH
set -Eeuo pipefail

export xv_cxl_lib_path="/tools/Xilinx/Vivado/2024.2/data/xsim"
export xv_cxl_ip_path="$xv_cxl_lib_path/ip"
export xv_cpt_lib_path="/tools/Xilinx/Vivado/2024.2/data/simmodels/xsim/2024.2/lnx64/9.3.0/systemc/protected"
xv_ext_lib_path="/tools/Xilinx/Vivado/2024.2/data/simmodels/xsim/2024.2/lnx64/9.3.0/ext"
export CHESSDIR="$XILINX_VITIS/aietools/tps/lnx64/target/chessdir"
xv_lib_path="/tools/Xilinx/Vivado/2024.2/lib/lnx64.o/Ubuntu/22:/tools/Xilinx/Vivado/2024.2/lib/lnx64.o/Ubuntu:/tools/Xilinx/Vivado/2024.2/lib/lnx64.o"

xv_ref_path=${VIVADO_LOC:-"/tools/Xilinx/Vivado/2024.2"}
xv_lib_path="$xv_ref_path/lib/lnx64.o/Default:$xv_ref_path/lib/lnx64.o"

export LD_LIBRARY_PATH=$PWD:$xv_lib_path:$xv_ref_path/data/xsim/ip/noc_sc_v1_0_0:$xv_ref_path/data/simmodels/xsim/2024.2/lnx64/9.3.0/ext/protobuf:$xv_ref_path/data/xsim/ip/sim_qdma_cpp_v1_0:$xv_ref_path/data/xsim/ip/axi_tlm_ext_v1_0:$xv_ref_path/data/xsim/ip/remote_port_c_v4:$xv_ref_path/data/xsim/ip/xtlm_ipc_v1_0:$xv_ref_path/data/xsim/ip/sim_qdma_sc_v1_0:$xv_ref_path/data/xsim/ip/xtlm_ap_ctrl_v1_0:$xv_ref_path/data/xsim/ip/xtlm_simple_interconnect_v1_0:$xv_ref_path/data/xsim/ip/common_cpp_v1_0:$xv_ref_path/data/xsim/ip/debug_tcp_server_v1:$xv_ref_path/data/xsim/ip/common_rpc_v1:$xv_ref_path/data/simmodels/xsim/2024.2/lnx64/9.3.0/systemc/protected/noc_v1_0_0:$xv_ref_path/data/xsim/ip/xtlm:$xv_ref_path/data/xsim/ip/aie_ps_v1_0:$xv_ref_path/data/xsim/ip/remote_port_sc_v4:$xv_ref_path/data/xsim/ip/pl_fileio_v1_0_0:$xv_ref_path/data/xsim/ip/aie_xtlm_v1_0_0:$xv_ref_path/data/xsim/ip/rwd_tlmmodel_v1:$xv_ref_path/data/xsim/ip/emu_perf_common_v1_0:$XILINX_VITIS/aietools/lib/lnx64.o:$LD_LIBRARY_PATH

# simulate design
echo "xsim vitis_design_wrapper_sim_wrapper_behav -key {Behavioral:sim_1:Functional:vitis_design_wrapper_sim_wrapper} -tclbatch vitis_design_wrapper_sim_wrapper.tcl -protoinst "protoinst_files/bd_57a1.protoinst" -protoinst "protoinst_files/bd_27ec.protoinst" -protoinst "protoinst_files/bd_9a4a.protoinst" -protoinst "protoinst_files/bd_e87b.protoinst" -protoinst "protoinst_files/bd_05a5.protoinst" -protoinst "protoinst_files/bd_a751.protoinst" -protoinst "protoinst_files/bd_e429.protoinst" -protoinst "protoinst_files/bd_931e.protoinst" -protoinst "protoinst_files/bd_93ee.protoinst" -protoinst "protoinst_files/vitis_design.protoinst" -protoinst "protoinst_files/xlnoc.protoinst" -log simulate.log $*"
xsim vitis_design_wrapper_sim_wrapper_behav -key {Behavioral:sim_1:Functional:vitis_design_wrapper_sim_wrapper} -tclbatch vitis_design_wrapper_sim_wrapper.tcl -protoinst "protoinst_files/bd_57a1.protoinst" -protoinst "protoinst_files/bd_27ec.protoinst" -protoinst "protoinst_files/bd_9a4a.protoinst" -protoinst "protoinst_files/bd_e87b.protoinst" -protoinst "protoinst_files/bd_05a5.protoinst" -protoinst "protoinst_files/bd_a751.protoinst" -protoinst "protoinst_files/bd_e429.protoinst" -protoinst "protoinst_files/bd_931e.protoinst" -protoinst "protoinst_files/bd_93ee.protoinst" -protoinst "protoinst_files/vitis_design.protoinst" -protoinst "protoinst_files/xlnoc.protoinst" -log simulate.log $*

