#include <algorithm>
#include <cmath>
#include <cstdio>
#include <fstream>
#include <iostream>
#include <map>
#include <string>

#include "rtda_split_top.h"

// Required by nnet_helpers.h
namespace nnet {
bool trace_enabled = false;
std::map<std::string, void*>* trace_outputs = nullptr;
size_t trace_type_size = sizeof(double);
}

static bool read_floats(const char* path, float* buf, int n) {
    std::ifstream f(path);
    if (!f.is_open()) {
        std::cerr << "ERROR: cannot open " << path << "\n";
        return false;
    }
    for (int i = 0; i < n; i++) {
        if (!(f >> buf[i])) {
            std::cerr << "ERROR: only read " << i << "/" << n << " values from " << path << "\n";
            return false;
        }
    }
    return true;
}

int main() {
    // embed_input.txt: values stored one per line.
    // Format from notebook: first N_TRACKS*8 values → reshape(N_TRACKS,8) → take cols 0:INPUT_SIZE
    const int STRIDE = 8;  // original data has 8 values per track
    float raw[N_TRACKS * STRIDE];
    if (!read_floats("embed_input.txt", raw, N_TRACKS * STRIDE)) return 1;

    float track_data[N_TRACKS * INPUT_SIZE];
    for (int j = 0; j < N_TRACKS; j++)
        for (int i = 0; i < INPUT_SIZE; i++)
            track_data[j * INPUT_SIZE + i] = raw[j * STRIDE + i];

    float result[OUT_DIM];
    rtda_split_top(track_data, result, N_TRACKS, /*reset=*/true);

    // Primary reference: hls_27dim.txt — the fixed-point (ap_fixed<16,6>) reference
    // generated by the mlo_hsl.ipynb notebook running the same hls4ml models.
    // This should match to numerical noise only (~1e-6).
    // keras_27dim.txt (float32) will differ by ~0.025 due to quantization — that is expected.
    float ref_hls[OUT_DIM], ref_keras[OUT_DIM];
    bool have_hls   = read_floats("hls_27dim.txt",   ref_hls,   OUT_DIM);
    bool have_keras = read_floats("keras_27dim.txt",  ref_keras, OUT_DIM);

    printf("\n%4s  %12s  %12s  %12s  %12s\n",
           "dim", "csim", "hls_ref", "diff_hls", "diff_keras");
    printf("%-4s  %-12s  %-12s  %-12s  %-12s\n",
           "---", "----", "-------", "--------", "-----------");

    float max_diff_hls = 0.0f, max_diff_keras = 0.0f;
    for (int k = 0; k < OUT_DIM; k++) {
        float dh = have_hls   ? std::abs(result[k] - ref_hls[k])   : -1.0f;
        float dk = have_keras ? std::abs(result[k] - ref_keras[k]) : -1.0f;
        if (dh > max_diff_hls)   max_diff_hls   = dh;
        if (dk > max_diff_keras) max_diff_keras  = dk;
        printf("%4d  %12.6f  %12.6f  %12.6f  %12.6f\n",
               k, result[k],
               have_hls   ? ref_hls[k]   : 0.0f, dh,
               have_keras ? dk : -1.0f);
    }

    printf("\nmax|diff| vs hls_27dim.txt   (fixed-pt ref) = %.2e  [should be ~0]\n", max_diff_hls);
    printf("max|diff| vs keras_27dim.txt (float32  ref) = %.4f  [expected ~0.02 quantization]\n", max_diff_keras);

    // Pass criterion: match the fixed-point reference to within floating-point noise
    const float PASS_THRESHOLD = 1e-4f;
    if (have_hls && max_diff_hls < PASS_THRESHOLD) {
        printf("PASS\n");
        return 0;
    } else if (!have_hls) {
        printf("WARN: hls_27dim.txt not found, cannot verify\n");
        return 0;
    } else {
        printf("FAIL (max|diff| vs hls ref = %.2e, threshold %.2e)\n", max_diff_hls, PASS_THRESHOLD);
        return 1;
    }
}
