#pragma once
#include <cstdint>

// config_gen.h is generated by the Makefile
#include "config_gen.h" 

#ifdef USE_INT16
using int16 = int16_t;
using DATA_TYPE = int16;
#else
using DATA_TYPE = float;
#endif
