##############################################################
# rtda_split_project.tcl -- Vitis HLS project for the PL-only RTDA design
#
#   vitis_hls rtda_split_project.tcl [csim|csynth|cosim|cosim_only|kernels]
#
#     csim        C simulation against the native model
#     csynth      C->RTL synthesis (resources + timing)
#     cosim       csynth + RTL co-simulation
#     cosim_only  RTL co-simulation reusing an existing csynth
#     kernels     csynth + export XO and IP catalog
#
# Driven from ../Makefile, which passes the fixed-point format and the
# testbench settings through the environment so that a `make csynth AP_W=18`
# and the native model can never be built from different definitions.
##############################################################

set PROJ_DIR [file dirname [file normalize [info script]]]

# Vendored from hls_projects/ -- see ../../pl_fixed/pl/firmware/. That tree is
# generated by a notebook and is not tracked by git, so depending on it at
# build time meant a clean clone could not synthesise.
set FW_DIR   [file join $PROJ_DIR firmware]

set part_name "xcve2802-vsvh1760-2MP-e-S"
set top_fn    "rtda_split_top"
# A BARE NAME on purpose: the project lands in the CWD, which is pl_fixed/
# because ../Makefile invokes vitis_hls from there. Making it absolute so it
# sat under pl/ instead broke csim -- HLS added the six design files to the
# project and then linked only the testbench, giving
# "ld.lld: error: undefined symbol: rtda_split_top". `make clean` removes it
# from the right place instead.
set prj_name  "rtda_split_hls"

if {[llength $argv] > 0} { set command [lindex $argv 0] } else { set command "csim" }

# --- settings from the Makefile -------------------------------------------
proc env_or {name default} {
    if {[info exists ::env($name)] && $::env($name) ne ""} { return $::env($name) }
    return $default
}
set AP_DEFS   [env_or RTDA_AP_DEFS ""]
set STIMULUS  [env_or RTDA_STIMULUS [file normalize "$PROJ_DIR/../../testdata/embed_input_50000.txt"]]
set TB_EVENTS [env_or RTDA_EVENTS 2]
set TB_WARMUP [env_or RTDA_WARMUP 3]
set REFERENCE [file normalize "$PROJ_DIR/../native/tb_means.txt"]

puts "*****  format defines : $AP_DEFS"
puts "*****  stimulus       : $STIMULUS"
puts "*****  tb events      : $TB_EVENTS   warmup: $TB_WARMUP"

set cflags "-I${FW_DIR} -I${PROJ_DIR}/src -std=c++14 $AP_DEFS"
# Paths are NOT passed as -D string macros. Their quotes do not survive Tcl
# plus the csim.mk that Vitis generates, and the path then arrives at the
# compiler as bare identifiers. The testbench and nnet_helpers both read them
# from the environment instead; ../Makefile exports RTDA_STIMULUS,
# RTDA_TB_REFERENCE, RTDA_EVENTS, RTDA_WARMUP and RTDA_WEIGHTS_DIR.
set tbflags "$cflags"

if {$command eq "cosim_only"} {
    open_project ${prj_name}
} else {
    open_project -reset ${prj_name}
}

set_top ${top_fn}

add_files ${PROJ_DIR}/src/rtda_split_top.cpp  -cflags $cflags
add_files ${PROJ_DIR}/src/embed_proxy.cpp     -cflags $cflags
add_files ${PROJ_DIR}/src/solver0_proxy.cpp   -cflags $cflags
add_files ${PROJ_DIR}/src/solver1_proxy.cpp   -cflags $cflags
add_files ${PROJ_DIR}/src/solver2_proxy.cpp   -cflags $cflags
add_files ${PROJ_DIR}/src/output_proxy.cpp    -cflags $cflags

add_files -tb ${PROJ_DIR}/src/rtda_split_tb.cpp -cflags $tbflags

if {$command eq "cosim_only"} {
    open_solution "solution1"
} else {
    open_solution -flow_target vitis "solution1"
    set_part $part_name
    create_clock -period 6.667 -name default
    config_compile -name_max_length 80
    set_clock_uncertainty 0.5 default
}

switch $command {
    csim {
        puts "***** C SIMULATION *****"
        csim_design
        puts "***** C SIMULATION DONE *****"
    }
    csynth {
        puts "***** C/RTL SYNTHESIS *****"
        csynth_design
        puts "***** C/RTL SYNTHESIS DONE *****"
    }
    cosim {
        puts "***** C/RTL CO-SIMULATION (with synthesis) *****"
        csynth_design
        cosim_design -rtl verilog -trace_level none -disable_deadlock_detection
        puts "***** CO-SIMULATION DONE *****"
    }
    cosim_only {
        puts "***** C/RTL CO-SIMULATION (reusing existing csynth) *****"
        cosim_design -rtl verilog -trace_level none -disable_deadlock_detection
        puts "***** CO-SIMULATION DONE *****"
    }
    kernels {
        puts "***** EXPORT XO + IP CATALOG *****"
        file mkdir ${PROJ_DIR}/ip
        csynth_design
        export_design -format xo -output ${PROJ_DIR}/ip/rtda_split.xo
        # NO ip_catalog export. It is a SECOND full RTL-to-IP run of the same
        # design -- measured at 1 h 12 m, the same as the xo export it follows --
        # and nothing consumes its output. ../Makefile links $(PL_XO) and only
        # $(PL_XO); grep finds rtda_split_ip nowhere else in the tree. It came
        # from archive/pl/track_average_project.tcl, where a hand-built Vivado
        # project did need an IP catalog entry.
        #
        # If you ever want the IP for a manual block design, run it on its own:
        #   vitis_hls -e 'open_project rtda_split_hls; open_solution solution1; \
        #                 export_design -format ip_catalog -output pl/ip/rtda_split_ip'
        puts "***** EXPORT DONE *****"
    }
    default {
        puts "ERROR: unknown command '$command'"
        puts "Usage: vitis_hls rtda_split_project.tcl \[csim|csynth|cosim|cosim_only|kernels\]"
        exit 1
    }
}

close_project
exit
