#!/usr/bin/env python
"""Emit the PL flow's weight files from model/weights_fp32/.

    ./gen_weights.py          # write pl/weights/*.txt and firmware/*/weights/*.h
    ./gen_weights.py --check  # verify what is on disk, write nothing

WHY THIS EXISTS
`pl/weights/*.txt` used to be 36 symlinks into `hls_projects/split_*/firmware/
weights/`, which is generated by a notebook and is not tracked by git. So the
tracked links pointed at untracked content: deleting hls_projects/ broke both
csim and synthesis, and there was no check that those weights were still the
same ones the AIE flow uses. (They were -- verified to 5e-09 -- but by luck.)

Now both forms come from model/weights_fp32/, the same directory the AIE graph
and the reference model read.

TWO LAYOUT CONVERSIONS, and they are the whole content of this file:

  1. TRANSPOSE. The reference stores dense weights (n_in, n_out). hls4ml's
     nnet::dense indexes them (n_out, n_in). Getting this backwards produces a
     network that runs, produces plausible numbers, and is wrong.

  2. THE SOLVER SPLIT. The reference keeps solver dense_0 as one (256, 128)
     matrix because the AIE feeds it a roll-concat. The PL flow computes two
     128->128 denses and adds them, so rows 0..127 become `w<n>` (current
     track) and rows 128..255 become `w<n+2>` (previous track). Same
     arithmetic, different decomposition. Only the current branch carries the
     bias; the previous branch's is the zero ap_uint<1> `b5`.

The hls4ml file names (w2, b2, w3, w5, w9, w12, w15, ...) are ONNX initializer
indices, not layer numbers. NAMES below is the only place that mapping is
written down.
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

import numpy as np

HERE = Path(__file__).resolve().parent
REPO = HERE.parent
sys.path.insert(0, str(REPO))
from model import weights as MW      # noqa: E402

TXT_DIR = HERE / 'pl' / 'weights'
FW_DIR = HERE / 'pl' / 'firmware'

# (file stem, block dir, source tensor, kind)  kind: 'w' transposed, 'b' as-is
NAMES = [
    # embed
    ('emb_w2',  'embed',   'emb_d0',      'w'),
    ('emb_b2',  'embed',   'emb_d0',      'b'),
    ('emb_w5',  'embed',   'emb_d1',      'w'),
    ('emb_b5',  'embed',   'emb_d1',      'b'),
    # output dense 128 -> 27
    ('out_w2',  'output',  'out',         'w'),
    ('out_b2',  'output',  'out',         'b'),
]
for s in range(3):
    NAMES += [
        (f's{s}_w3',  f'solver{s}', f's{s}_d0_curr', 'w'),   # current track
        (f's{s}_b3',  f'solver{s}', f's{s}_d0',      'b'),
        (f's{s}_w5',  f'solver{s}', f's{s}_d0_prev', 'w'),   # previous track
        (f's{s}_b5',  f'solver{s}', None,            'z'),   # zero, ap_uint<1>
        (f's{s}_w9',  f'solver{s}', f's{s}_d1',      'w'),
        (f's{s}_b9',  f'solver{s}', f's{s}_d1',      'b'),
        (f's{s}_w12', f'solver{s}', f's{s}_d2',      'w'),
        (f's{s}_b12', f'solver{s}', f's{s}_d2',      'b'),
        (f's{s}_w15', f'solver{s}', f's{s}_d3',      'w'),
        (f's{s}_b15', f'solver{s}', f's{s}_d3',      'b'),
    ]

# The stem the firmware headers use (they are per-block, so unprefixed).
def fw_stem(stem):
    return stem.split('_', 1)[1]


# The C++ type each array is DECLARED as in the firmware. Almost everything is
# model_default_t, but the solvers' previous-track branch has a structurally
# zero bias that hls4ml typed ap_uint<1> (`bias5_t`) so it costs nothing. Emit
# it with the wrong type and nnet::dense stops matching its own config.
def decl_type(stem):
    return 'bias5_t' if stem.endswith('_b5') and stem[0] == 's' else 'model_default_t'


def tensor(stem, blk, src, kind, W, B):
    if kind == 'z':
        return np.zeros(MW.H)
    if kind == 'b':
        return B[src]
    a = W[src]
    return a.T.copy()          # (n_in, n_out) -> (n_out, n_in)


def write_txt(path, a):
    path.write_text(', '.join(f'{v:.10f}' for v in a.ravel()) + '\n')


def write_h(path, name, a, ctype, comment):
    body = ', '.join(f'{v:.10f}' for v in a.ravel())
    guard = name.upper() + '_H_'
    path.write_text(
        f'// {comment}\n'
        f'//Min {a.min():.12f}\n//Max {a.max():.12f}\n'
        f'//Number of zeros {int((a == 0).sum())}\n\n'
        f'#ifndef {guard}\n#define {guard}\n\n'
        f'#ifndef __SYNTHESIS__\n'
        f'{ctype} {name}[{a.size}];\n'
        f'#else\n'
        f'{ctype} {name}[{a.size}] = {{{body}}};\n'
        f'#endif\n\n#endif\n')


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--check', action='store_true',
                    help='verify the files on disk against the model, write nothing')
    ap.add_argument('--tol', type=float, default=1e-8)
    a = ap.parse_args()

    W, B = MW.load()
    TXT_DIR.mkdir(parents=True, exist_ok=True)

    worst, n = 0.0, 0
    for stem, blk, src, kind in NAMES:
        arr = tensor(stem, blk, src, kind, W, B)
        txt = TXT_DIR / f'{stem}.txt'

        if a.check:
            if not txt.exists():
                print(f'  MISSING {txt}')
                worst = float('inf')
                continue
            got = np.fromstring(txt.read_text().replace(',', ' '), sep=' ')
            if got.size != arr.size:
                print(f'  SIZE    {stem}: {got.size} on disk, {arr.size} expected')
                worst = float('inf')
                continue
            d = np.abs(got - arr.ravel()).max()
            worst = max(worst, d)
            n += 1
            if d > a.tol:
                print(f'  DIFFERS {stem}: max|diff| = {d:.3e}')
            continue

        # a symlink must be replaced, not written through
        if txt.is_symlink():
            txt.unlink()
        write_txt(txt, arr)

        hdir = FW_DIR / blk / 'weights'
        hdir.mkdir(parents=True, exist_ok=True)
        st = fw_stem(stem)
        write_h(hdir / f'{st}.h', st, arr, decl_type(stem),
                f'{stem} <- model/weights_fp32 ({src or "zeros"}), '
                f'shape {arr.shape}, written by pl_fixed/gen_weights.py')
        write_txt(hdir / f'{st}.txt', arr)
        n += 1

    if a.check:
        ok = worst <= a.tol
        print(f'  {n} tensors checked against {MW.DEFAULT_DIR}')
        print(f'  worst max|diff| = {worst:.3e}   {"ok" if ok else "FAIL"}')
        raise SystemExit(0 if ok else 1)

    print(f'  wrote {n} tensors -> {TXT_DIR} and {FW_DIR}/*/weights/')
    print(f'  source: {MW.DEFAULT_DIR}')


if __name__ == '__main__':
    main()
